---
sidebar: sidebar 
permalink: concept-before-you-begin-to-deploy-gfc.html 
keywords: global file cache, core, edge, management server 
summary: BlueXPのエッジキャッシングをクラウドやリモートオフィスに導入する前に、いくつもの要件について理解しておく必要があります。 
---
= BlueXPエッジキャッシングの導入を開始する前に
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXPのエッジキャッシングをクラウドやリモートオフィスに導入する前に、いくつもの要件について理解しておく必要があります。



== BlueXPエッジキャッシングコアの設計に関する考慮事項

要件によっては、BlueXPエッジキャッシュファブリックを作成するために、1つ以上のBlueXPエッジキャッシュコアインスタンスの導入が必要になる場合があります。Coreインスタンスは、分散されたBlueXPエッジキャッシングエッジインスタンスとデータセンターのファイルサーバリソース（ファイル共有、フォルダ、ファイルなど）の間でトラフィックフローを転送するように設計されています。

BlueXPのエッジキャッシュ環境を設計するときは、拡張性、リソースの可用性、冗長性の観点から、環境に最適なソリューションを判断する必要があります。BlueXPエッジキャッシングコアは、次の方法で導入できます。

* スタンドアロンインスタンス
* 負荷分散設計（コールドスタンバイ）


を参照してください <<サイジングガイドライン>> Edge インスタンスの最大数と各構成でサポート可能な合計ユーザ数を理解するには、次の手順を実行します。

エンタープライズ環境に最適なオプションについては、ネットアップのソリューションエンジニアにお問い合わせください。



== サイジングガイドライン

初期システムを構成する際には、サイジングに関するいくつかのガイドラインについて留意する必要があります。システムを最適に使用するには、使用履歴が蓄積してからこれらの比率を再確認する必要があります。次のようなものがあり

* エッジ/コア比率
* 分散ユーザー/エッジ比率
* 分散ユーザ数/コア数の比率




=== コアインスタンスごとのエッジインスタンスの数

ガイドラインでは、BlueXPエッジキャッシングコアインスタンスあたり最大10個のEdgeインスタンス、BlueXPエッジキャッシングコアインスタンスあたり最大20個のEdgeインスタンスを推奨しています。これは、最も一般的なワークロードのタイプと平均ファイルサイズに大きく依存します。より一般的なワークロードでは、コアごとにEdgeインスタンスを追加できますが、このような場合は、ファイルセットの種類とサイズに応じて、EdgeインスタンスとCoreインスタンスの数を正しくサイジングする方法をアカウント担当者に確認してください。


NOTE: BlueXPのエッジキャッシングのエッジとコアの複数のインスタンスを同時に活用して、要件に応じてインフラをスケールアウトできます。



=== Edge インスタンスごとの同時ユーザー数

BlueXPのエッジキャッシングエッジは、キャッシングアルゴリズムやファイルレベルの差分処理の面倒な処理に対応します。1つのEdgeインスタンスで、dedicated_physical_Edgeインスタンスあたり最大500ユーザ、dedicated_virtual_deploymentsで最大300ユーザを処理できます。これは、最も一般的なワークロードのタイプと平均ファイルサイズに大きく依存します。大規模なコラボレーションファイルタイプの場合は、BlueXPエッジキャッシングエッジの下限（物理環境または仮想環境に応じて）あたりの最大ユーザ数の50%をガイドしてください。平均ファイルサイズが1MB未満の一般的なOfficeアイテムについては、Edgeの上限境界あたり100%のユーザーをガイドしてください(物理環境または仮想環境によって異なります)。


NOTE: BlueXPのエッジキャッシュエッジは、仮想インスタンスと物理インスタンスのどちらで実行されているかを検出し、ローカルの仮想ファイル共有へのSMB接続の最大数を300または500に制限します。



=== コアインスタンスあたりの同時ユーザー数

BlueXPのエッジキャッシュコアインスタンスは非常に拡張性に優れており、コアあたりの同時ユーザ数は3、000ユーザを推奨します。これは、最も一般的なワークロードのタイプと平均ファイルサイズに大きく依存します。

エンタープライズ環境に最適なオプションについては、ネットアップのソリューションエンジニアにお問い合わせください。



== 前提条件

このセクションで説明する前提条件は、クラウドにインストールされているコンポーネント（BlueXP Edge Caching Management ServerとBlueXP Edge Caching Core）についてです。

BlueXPエッジキャッシングエッジの前提条件については、link：download-gfc-resources.html#bluexp-edge caching-edge-requirements [こちら]を参照してください。



=== ストレージプラットフォーム（ボリューム）

バックエンドストレージプラットフォームは、この例では導入したCloud Volumes ONTAP インスタンスで、SMBファイル共有を提供します。BlueXPのエッジキャッシュで公開される共有では、NTFS権限で権限を制限しながら、共有レベルで「Everyone」グループにフルコントロールを許可する必要があります。

Cloud Volumes ONTAP インスタンスで SMB ファイル共有をセットアップしていない場合は、インストール時に設定できるように次の情報を用意しておく必要があります。

* Active Directory ドメイン名、ネームサーバの IP アドレス、 Active Directory 管理者のクレデンシャル。
* 作成するボリュームの名前とサイズ、ボリュームを作成するアグリゲートの名前、および共有名。


ボリュームは、アプリケーション用のデータセットの合計数に対応できるだけの大きさであり、データセットの拡張に合わせて拡張できることを推奨します。作業環境に複数のアグリゲートがある場合は、を参照してください https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-manage-aggregates.html["既存のアグリゲートの管理"^] をクリックして、新しいボリュームの空きスペースが最も多いアグリゲートを確認します。



=== BlueXPエッジキャッシング管理サーバ

BlueXPエッジキャッシング管理サーバでは、クラウドプロバイダサブスクリプションサービスに接続して次のURLにアクセスするために、HTTPS経由の外部アクセス（TCPポート443）が必要です。

* \ https://gfcproxyforcm-prod.azurewebsites.net/
* \ https://rest.zuora.com/v1/subscriptions/
* \ https://rest.zuora.com/oauth/token
* https://talonazuremicroservices.azurewebsites.net
* https://talonlicensing.table.core.windows.net


BlueXPエッジキャッシングソフトウェアが適切に動作するためには、このポートをWAN最適化デバイスやファイアウォール制限ポリシーから除外する必要があります。

BlueXPのエッジキャッシュ管理サーバでは、インスタンスに一意の（地理的な）NetBIOS名（GFC-MS1など）も必要です。


NOTE: 1台の管理サーバで、異なる作業環境に導入された複数のBlueXPエッジキャッシュコアインスタンスをサポートできます。BlueXPから導入した場合'それぞれの作業環境には独自のバックエンド・ストレージがあり'同じデータは含まれません



=== BlueXPエッジキャッシングコア

BlueXPのエッジキャッシングコアは、TCPポート6618~6630でリスンします。ファイアウォールまたはネットワークセキュリティグループ（ NSG ）の設定によっては、インバウンドポートルールを使用してこれらのポートへのアクセスを明示的に許可する必要があります。また、BlueXPエッジキャッシングソフトウェアが適切に動作するためには、これらのポートをWAN最適化デバイスやファイアウォール制限ポリシーから除外する必要があります。

BlueXPエッジキャッシングコアの要件は次のとおりです。

* インスタンスの一意な（地理的な） NetBIOS 名 （ GFC-CORE1 など）
* Active Directory ドメイン名
+
** インスタンスはActive Directoryドメインに参加する必要があります。
** インスタンスはBlueXPエッジキャッシングの特定のOrganizational Unit（OU；組織単位）で管理し、継承される企業GPOから除外する必要があります。


* サービスアカウント：コア上のサービスは、特定のドメインユーザーアカウントとして実行されます。このアカウント（サービスアカウントとも呼ばれます）には、BlueXPエッジキャッシュのコアインスタンスに関連付ける各SMBサーバに対する次の権限が必要です。
+
** プロビジョニングされたサービスアカウントはドメインユーザである必要があります。
+
ネットワーク環境における制限のレベルおよび GPO によっては、このアカウントにドメイン管理者権限が必要になる場合があります。

** Run As a Service 権限が必要です。
** パスワードは「無期限」に設定する必要があります。
** アカウントオプションの [ 次回ログオン時にパスワードを変更する必要があります ] を無効にします ( オフ ) 。
** これは、バックエンドファイルサーバの組み込みBackup Operatorsグループのメンバーである必要があります（これは、BlueXPを使用して展開すると自動的に有効になります）。






=== License Management Server の略

* BlueXPエッジキャッシングライセンス管理サーバ（LMS）は、Microsoft Windows Server 2016 Standard EditionまたはDatacenter Edition、またはWindows Server 2019 Standard EditionまたはDatacenter Edition、できればデータセンターまたはクラウドのBlueXPエッジキャッシングコアインスタンスで構成する必要があります。
* BlueXPエッジキャッシングLMSインスタンスを別途用意する必要がある場合は、最新のBlueXPエッジキャッシングソフトウェアインストールパッケージをMicrosoft Windows Serverインスタンスにインストールする必要があります。
* LMSインスタンスは、HTTPS（TCPポート443）を使用してサブスクリプションサービス（パブリックインターネット）に接続できる必要があります。
* コアインスタンスとエッジインスタンスは、 HTTPS （ TCP ポート 443 ）を使用して LMS インスタンスに接続する必要があります。




=== ネットワーク（外部アクセス）

BlueXPエッジキャッシングLMSでは、次のURLへのHTTPS（TCPポート443）経由の外部アクセスが必要です。

* GFC サブスクリプションベースのライセンスを使用している場合：
+
** \ https://rest.zuora.com/v1/subscriptions/<subscription-no>
** \ https://rest.zuora.com/oauth/token


* NetApp NSS ベースのライセンスを使用している場合：
+
** \ https://login.netapp.com
** \ https://login.netapp.com/ms_oauth/oauth2/endpoints
** \ https://login.netapp.com/ms_oauth/oauth2/endpoints/oauthservice/tokens


* ネットアップの従来型ライセンスを使用している場合：
+
** https://talonazuremicroservices.azurewebsites.net
** https://talonlicensing.table.core.windows.net






=== ネットワーキング

* ファイアウォール：BlueXPのエッジキャッシングのエッジインスタンスとコアインスタンスの間でTCPポートを許可する必要があります。
* BlueXPエッジキャッシュTCPポート：443（HTTPS）、6618~6630。
* ネットワーク最適化デバイス（Riverbed Steelheadなど）は、BlueXPのエッジキャッシュ固有のポート（TCP 6618~6630）をパススルーするように設定する必要があります。

