---
sidebar: sidebar 
permalink: download-gfc-resources.html 
keywords: global file cache, edge 
summary: リモートオフィスにBlueXP Edge Caching Edgeソフトウェアをインストールする前に、いくつもの要件について理解しておく必要があります。 
---
= BlueXPエッジキャッシングエッジインスタンスの導入を開始する前に
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
リモートオフィスにBlueXP Edge Caching Edgeソフトウェアをインストールする前に、いくつもの要件について理解しておく必要があります。



== 必要なリソースをダウンロード

ブランチオフィスで使用するBlueXPエッジキャッシング仮想テンプレート、ソフトウェアインストールパッケージ、その他のリファレンスドキュメントをダウンロードします。

* Windows Server 2016 仮想テンプレート：
+
https://repo.cloudsync.netapp.com/gfc/2k16-2_3_0-55.zip["NetApp GFC を含む Windows Server * 2016.OVA （ VMware vSphere 6.5 以降）"^]
https://repo.cloudsync.netapp.com/gfc/2k16_GFC_2_3_0_55IMAGE.zip["NetApp GFC を含む Windows Server 2016-0x （ Microsoft Hyper-V ）"^]

* Windows Server 2019 仮想テンプレート：
+
https://repo.cloudsync.netapp.com/gfc/2k19-2_3_0-55.zip["Windows Server 206.OVA （ NetApp GFC を含む）（ VMware vSphere 6.5 以降）"^]
https://repo.cloudsync.netapp.com/gfc/2k19_GFC_2_3_0_55IMAGE.zip["NetApp GFC （ Microsoft Hyper-V ）を含む Windows Server 19VHDX"^]

* BlueXP Edgeキャッシュエッジソフトウェア：
+
https://repo.cloudsync.netapp.com/gfc/GFC-2-3-0-55-Release.exe["NetApp GFC ソフトウェアインストールパッケージ（ .EXE ）"^]

* Cloud Insights のグローバルファイルキャッシュダッシュボード：
+
https://repo.cloudsync.netapp.com/gfc/ci-gfc-dashboards.zip["NetApp GFC Cloud Insights ダッシュボード（.ZIP）"]

* グローバルファイルキャッシュのドキュメント：
+
https://repo.cloudsync.netapp.com/gfc/Global%20File%20Cache%202.3.0%20User%20Guide.pdf["NetApp Global File Cache User Guide（ .pdf ）"^]



link:task-deploy-gfc-edge-instances.html#update-bluexp-edge-caching-edge-software["次の手順を実行します"] をクリックして、BlueXP Edge Caching Edgeソフトウェアをアップグレードしてください。


NOTE: Windows Server 2016にBlueXPエッジキャッシュを導入する場合は、.NET Framework 4.8とWindows WebView2フレームワークを使用する必要があります。



== BlueXPエッジキャッシュエッジの設計と導入

要件によっては、ブランチオフィスでの同時ユーザーセッションに基づいて、1つまたは複数のEdgeインスタンスを展開する必要があります。Edgeインスタンスは、ブランチオフィス内のエンドユーザに仮想ファイル共有を提供します。この共有は、関連付けられているBlueXPエッジキャッシングコアインスタンスから透過的に拡張されています。BlueXPエッジキャッシングエッジにはが含まれている必要があります `D:\` NTFS ボリューム。ブランチオフィスにキャッシュされたファイルが格納されます。


NOTE: BlueXPのエッジキャッシュエッジについては、を理解しておくことが重要です link:concept-before-you-begin-to-deploy-gfc.html#sizing-guidelines["サイジングガイドライン"]。これにより、BlueXPエッジキャッシュの導入に適した設計を行うことができます。また、拡張性、リソースの可用性、および冗長性の観点から、環境に最適なものを判断する必要があります。



=== BlueXPのエッジキャッシュエッジインスタンス

BlueXPのエッジキャッシュエッジインスタンスを導入する場合は、Windows Server 2016 StandardまたはDatacenter Edition、Windows Server 2019 StandardまたはDatacenter Editionを導入するか、エッジキャッシュを使用して、単一のVMをプロビジョニングする必要があります `.OVA` または `.VHD` テンプレート。選択したWindows ServerオペレーティングシステムとBlueXPエッジキャッシングソフトウェアが含まれます。



==== クイックステップ

. BlueXPエッジキャッシュ仮想テンプレート、Windows Server 2016 VM、Windows Server 2019 Standard EditionまたはDatacenter Editionを導入します。
. VM がネットワークに接続され、ドメインに参加し、 RDP を介してアクセス可能であることを確認します。
. 最新のBlueXP Edge Caching Edgeソフトウェアをインストールします。
. BlueXPのエッジキャッシュ管理サーバとコアインスタンスを特定します。
. BlueXP Edge Caching Edgeインスタンスを設定します。




== BlueXPのエッジキャッシュエッジの要件

BlueXPのエッジキャッシュエッジは、Windows Server 2016と2019をサポートするすべてのプラットフォームで機能するように設計されており、企業のリモートオフィスなどにシンプルなIT環境を提供します。非常に重要なのは、既存のハードウェアインフラ、仮想化環境、ハイブリッド/パブリッククラウド環境がいくつかの基本レベルの要件を満たしていれば、ほぼすべてのケースで、BlueXPのエッジキャッシングを導入できることです。

Edgeが最適に機能するには、次のハードウェアおよびソフトウェアリソースが必要です。全体的なサイジングガイドラインの詳細については、を参照してください link:concept-before-you-begin-to-deploy-gfc.html#sizing-guidelines["サイジングガイドライン"]。



=== 強化されたサーバーアプライアンス

BlueXPエッジキャッシュインストールパッケージを使用すると、すべてのMicrosoft Windows Serverインスタンスに強化されたソフトウェアアプライアンスを作成できます。BlueXPエッジキャッシュパッケージをアンインストールしないでください。BlueXPのエッジキャッシュをアンインストールすると、サーバインスタンスの機能に影響し、サーバインスタンスの完全なリビルドが必要になる場合があります。



=== 物理ハードウェアの要件

* 8個以上のCPUコア
* 32GB以上のRAM
* 専用のシングルまたは冗長 1 Gbps NIC
* 10K RPM SAS HDD または SSD （推奨）
* ライトバックキャッシュ機能が有効になっている RAID コントローラ




=== 仮想導入の要件

ハイパーバイザープラットフォームは、ストレージサブシステムの観点からはパフォーマンス低下の影響を受けることがわかっています（レイテンシなど）。BlueXPのエッジキャッシングを使用してパフォーマンスを最適化するには、SSDを搭載した物理サーバインスタンスを使用することを推奨します。

仮想環境で最大限のパフォーマンスを実現するには、物理ホストの要件に加えて、次の要件とリソースリザベーションを満たす必要があります。

Microsoft Hyper-V 2012 R2 以降：

* Processor（CPU）：CPUは* Static *：最小：8 vCPUコアに設定する必要があります。
* メモリ（RAM）：最小：32GB（* Static *に設定）。
* ハードディスクのプロビジョニング：ハードディスクは * 固定ディスク * として構成する必要があります。


VMware vSphere 6.x 以降：

* プロセッサ（ CPU ）： CPU サイクルの予約を設定する必要があります。最小：8個のvCPUコア（10000 MHz）
* メモリ（RAM）：最小：32 GBの予約。
* ハードディスクのプロビジョニング：
+
** ディスクプロビジョニングは「 * Thick provisioned Eager Zeroed * 」として設定する必要があります。
** ハードディスク共有は「 * 高」に設定する必要があります。
** Microsoft WindowsでBlueXPエッジキャッシュドライブがリムーバブルとして表示されないようにするには、vSphere Clientを使用してdevices.hotplugを* False *に設定する必要があります。


* ネットワーク：ネットワークインターフェイスは *VMXNET3* に設定する必要があります（ VM Tools が必要な場合があります）。


EdgeはWindows Server 2016および2019上で動作するため、仮想化プラットフォームはオペレーティングシステムをサポートするだけでなく、VMのゲストOSのパフォーマンスとVM ToolsなどのVMの管理を強化するユーティリティと統合する必要があります。



=== パーティションのサイジング要件

* C ： \- 最小 250GB （システム / ブートボリューム）
* D ： \ - 最小 1TB （グローバル・ファイル・キャッシュ・インテリジェント・ファイル・キャッシュ用の個別データ・ボリューム * ）


* 最小サイズは、アクティブデータセットの 2 倍です。キャッシュボリューム（ D ： \ ）は拡張が可能で、 Microsoft Windows NTFS ファイルシステムの制限によってのみ制限されます。



=== グローバルファイルキャッシュインテリジェントファイルキャッシュのディスク要件

グローバルファイルキャッシュインテリジェントファイルキャッシュディスク（ D ： \ ）のディスクレイテンシは、同時ユーザーあたり 0.5 ミリ秒未満の平均 I/O ディスクレイテンシと 1 MiBps のスループットを実現する必要があります。

詳細については、を参照してください https://repo.cloudsync.netapp.com/gfc/Global%20File%20Cache%202.3.0%20User%20Guide.pdf["『 NetApp Global File Cache User Guide 』を参照してください"^]。



=== ネットワーキング

* ファイアウォール：BlueXPエッジキャッシュのEdgeインスタンスとManagement ServerインスタンスとCoreインスタンスの間でTCPポートを許可する必要があります。
+
BlueXPエッジキャッシュTCPポート：443（HTTPS-LMS）、6618~6630。

* ネットワーク最適化デバイス（Riverbed Steelheadなど）は、BlueXPのエッジキャッシュ固有のポート（TCP 6618~6630）をパススルーするように設定する必要があります。




=== クライアントワークステーションとアプリケーションのベストプラクティス

BlueXPのエッジキャッシングは、お客様の環境に透過的に統合されるため、ユーザはクライアントワークステーションを使用してエンタープライズアプリケーションを実行し、一元化されたデータにアクセスできます。BlueXPのエッジキャッシングを使用すると、直接ドライブマッピングまたはDFSネームスペースを介してデータにアクセスできます。BlueXPのエッジキャッシングファブリック、インテリジェントなファイルキャッシング、およびソフトウェアの主な機能の詳細については、を参照してください link:concept-before-you-begin-to-deploy-gfc.html["BlueXPエッジキャッシングの導入を開始する前に"^] セクション。

最適なエクスペリエンスとパフォーマンスを確保するには、『グローバルファイルキャッシュユーザーガイド』に記載されている Microsoft Windows クライアントの要件およびベストプラクティスに準拠することが重要です。これは、すべてのバージョンの Microsoft Windows に適用されます。

詳細については、を参照してください https://repo.cloudsync.netapp.com/gfc/Global%20File%20Cache%202.3.0%20User%20Guide.pdf["『 NetApp Global File Cache User Guide 』を参照してください"^]。



=== ファイアウォールとアンチウイルスのベストプラクティス

BlueXPのエッジキャッシングでは、最も一般的なウィルス対策アプリケーションスイートがGlobal File Cacheと互換性があるかどうかを検証するために合理的な努力を払っていますが、ネットアップは、これらのプログラムまたはそれらに関連する更新、サービスパック、変更に起因する互換性の問題やパフォーマンスの問題を保証することはできず、責任を負いません。

BlueXPのエッジキャッシュが有効なインスタンス（CoreまたはEdge）には、監視ソリューションやウィルス対策ソリューションをインストールしたり適用したりしないことを推奨します。ソリューションをインストールするか、選択したか、またはポリシーに基づいて、次のベストプラクティスと推奨事項を適用する必要があります。一般的なウィルス対策スイートについては、の付録 A を参照してください https://repo.cloudsync.netapp.com/gfc/Global%20File%20Cache%202.3.0%20User%20Guide.pdf["『 NetApp Global File Cache User Guide 』を参照してください"^]。



=== ファイアウォールの設定

* Microsoft ファイアウォール：
+
** ファイアウォールの設定をデフォルトのままにします。
** 推奨事項：Microsoftファイアウォールの設定とサービスはデフォルトのオフのままにし、BlueXPのエッジキャッシュの標準インスタンスでは開始しないでください。
** 推奨事項： Microsoft のファイアウォール設定とサービスはデフォルト設定の on のままにし、ドメインコントローラの役割も実行する Edge インスタンスに対して開始します。


* 企業ファイアウォール：
+
** BlueXPエッジキャッシングコアインスタンスはTCPポート6618~6630でリスンし、BlueXPエッジキャッシングエッジインスタンスがこれらのTCPポートに接続できることを確認します。
** BlueXPのエッジキャッシュインスタンスでは、TCPポート443（HTTPS）でBlueXPのエッジキャッシュ管理サーバと通信する必要があります。


* BlueXPのエッジキャッシュの特定のポートをパススルーするようにネットワーク最適化ソリューション/デバイスを設定する必要があります。




=== ウィルス対策のベストプラクティス

ネットアップでは、Cylance、McAfee、Symantec、Sophos、Trend Micro、 Kaspersky、Crowd Strike、Cisco AMP、Tannium、Windows DefenderをBlueXPエッジキャッシングと組み合わせて使用します。ウィルス対策ソフトウェアは、ネットアップの認定を受けたもので、適切な除外リストが設定されている場合にのみサポートされます。の付録Aを参照してください https://repo.cloudsync.netapp.com/gfc/Global%20File%20Cache%202.3.0%20User%20Guide.pdf["『 NetApp Global File Cache User Guide 』を参照してください"^]


NOTE: Edgeアプライアンスにアンチウイルスを追加すると、ユーザーのパフォーマンスに10～20%の影響が生じる可能性があります。

詳細については、を参照してください https://repo.cloudsync.netapp.com/gfc/Global%20File%20Cache%202.3.0%20User%20Guide.pdf["『 NetApp Global File Cache User Guide 』を参照してください"^]。



==== 除外を設定します

ウイルス対策ソフトウェアまたはその他のサードパーティ製のインデックス付けまたはスキャンユーティリティでは、 Edge インスタンス上のドライブ D ： \ をスキャンしないでください。Edge サーバードライブ D:\ をスキャンすると、キャッシュネームスペース全体に対する多数のファイルオープン要求が発生します。これにより、データセンターで最適化されているすべてのファイルサーバに対して、 WAN 経由でファイルがフェッチされます。WAN 接続フラッディングおよび Edge インスタンス上の不要な負荷が発生すると、パフォーマンスが低下します。

D：\ドライブに加えて、BlueXPのエッジキャッシュ用の次のディレクトリとプロセスをすべてのウィルス対策アプリケーションから除外する必要があります。

* C ： \Program Files\TalonFAST\`
* C:\Program Files\TalonFAST\Bin\LMClientService.exe`
* C:\Program Files\TalonFAST\Bin\LMServerService.exe`
* C ： \Program Files\TalonFAST\Bin\Optimus.exe
* C ： \Program Files\TalonFAST\Bin\tafsexport.exe
* C:\Program Files\TalonFAST\Bin\tafsutils.exe`
* C ： \Program Files\TalonFAST\Bin\Tapp.exe`
* C ： \Program Files\TalonFAST\Bin\TappN.exe`
* C ： \Program Files\TalonFAST\Bin\FTLSummaryGenerator.exe`
* 'C:\Program Files\TalonFAST\Bin\GfcCIAgentService.exe'
* C ： \Program Files\TalonFAST\Bin\RFASTSetupWizard.exe`
* C ： \Program Files\TalonFAST\Bin\TService.exe`
* C ： \Program Files\TalonFAST\Bin\TUM.exe`
* C ： \Program Files\TalonFAST\FastDebugLogs\`
* C:\Windows\System32\drivers\tfast.sys
* '\\?\tafsMtP:\`or `\\?\tafsMtPt*`
* \\Device\TalonCacheFS\`
* \\?\GLOBALROOT\Device\TalonCacheFS\`
* \\?\GLOBALROOT\Device\TalonCacheFS\*`




== ネットアップサポートポリシー

BlueXPのエッジキャッシュインスタンスは、Windows Server 2016および2019プラットフォームで実行されるプライマリアプリケーションとして特別に設計されています。BlueXPのエッジキャッシュでは、ディスク、メモリ、ネットワークインターフェイス、 そしてこれらのリソースに高い需要を課すことができます。仮想環境では、メモリ / CPU の予約とハイパフォーマンスディスクが必要です。

* ブランチオフィス環境の場合、BlueXPのエッジキャッシングを実行するサーバでサポートされるサービスとアプリケーションは次のものに制限されます。
+
** DNS/DHCP
** Active Directoryドメインコントローラ（BlueXPのエッジキャッシュは別のボリュームに配置する必要があります）
** プリントサービス
** Microsoft System Center Configuration Manager （ SCCM ）
** BlueXPのエッジキャッシュで承認されたクライアント側システムエージェントとウィルス対策アプリケーション


* ネットアップのサポートとメンテナンスは、BlueXPのエッジキャッシングにのみ適用されます。
* データベースサーバやメールサーバなど、リソースを大量に消費する基幹業務生産性ソフトウェアはサポートされていません。
* BlueXP以外のエッジキャッシングソフトウェアは、お客様の責任において使用し、BlueXPエッジキャッシングを実行しているサーバにインストールする必要があります。
+
** サードパーティのソフトウェアパッケージが原因でソフトウェアやリソースがBlueXPエッジキャッシングと競合したり、パフォーマンスが低下したりした場合、ネットアップのサポート部門から、お客様にBlueXPエッジキャッシングを実行するサーバからソフトウェアを無効にするか削除するよう求められることがあります。
** BlueXPエッジキャッシングアプリケーションを実行しているサーバに追加されたソフトウェアのインストール、統合、サポート、アップグレードはすべてお客様の責任で行ってください。


* ウイルス対策ツールやライセンスエージェントなどのシステム管理ユーティリティ / エージェントは、共存できます。ただし、上記のサポート対象のサービスとアプリケーションを除き、これらのアプリケーションはBlueXPエッジキャッシングではサポートされないため、上記と同じガイドラインに従う必要があります。
+
** 追加されたすべてのソフトウェアのインストール、統合、サポート、アップグレードについては、お客様の責任となります。
** BlueXPのエッジキャッシングとソフトウェアやリソースの競合を引き起こしたり、その原因となっている可能性がある、またはその疑いがある他社製ソフトウェアパッケージをお客様がインストールした場合、BlueXPのエッジキャッシングのサポート部門がソフトウェアを無効化/削除する必要がある場合があります。



